spring:
  datasource:
    url: ${DOCK_JDBC_POSTGRES_DB}
    username: ${DOCK_POSTGRES_USERNAME}
    password: ${DOCK_POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${DOCK_REDIS_PASSWORD}