spring:
  application:
    name: np-shop
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
  messages:
    basename: messages
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
server:
  port: 8080

jwt:
  secret: a7f3k9mX2pQwR8vL5nJcYdEhBuTsGiZoA4eN6WqC1xDyPmFjKrHbVgUlSt0Owz
  expiration : 900000
base:
  api: /api/v1
paypal:
  return-url : https://drainable-unplanted-alive.ngrok-free.dev/api/paypal/capture
  cancel-url : https://drainable-unplanted-alive.ngrok-free.dev/api/paypal/cancel
  client:
    id: ARl_OI-bRaQXUHBjYwhoiIKv9UYv33biCCBr6ufJaMQLvobnRvWKvVXceSYknIP4SzFTU2IRsyfOkq6o
    secret: EIFEA-HfxAD9fFUMWBgr1zk5y9qmGL3o8ryqN5i-WISwTLsf__5bbjWsl-yf2pi-_FIlk7MGTHkuII1V
  mode: sandbox