spring:
  datasource:
    url: ${DEV_JDBC_POSTGRES_DB}
    username: ${DEV_POSTGRES_USERNAME}
    password: ${DEV_POSTGRES_PASSWORD}
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379
      password: ${DEV_REDIS_PASSWORD}
      ssl:
        enabled: true
